### ISSUE TITLE
Uncaught TypeError: Cannot read property 'column' of undefined

### ISSUE THREAD

**Issue by d3l1ght** [educator-io/trueautomation-atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [trueautomation-element-picker](https://github.com/educator-io/trueautomation-atom) package 2.1.8

### Stack Trace

Uncaught TypeError: Cannot read property 'column' of undefined

```
At /Users/delight/.atom/packages/trueautomation-element-picker/lib/trueautomation-atom.js:187

TypeError: Cannot read property 'column' of undefined
    at /packages/trueautomation-element-picker/lib/trueautomation-atom.js:187:52
    at Array.forEach (<anonymous>)
    at /packages/trueautomation-element-picker/lib/trueautomation-atom.js:185:40
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188425)
    at TextEditorComponent.setScrollLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:115645)
    at TextEditorComponent.setScrollRight (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:115904)
    at TextEditorComponent.autoscrollHorizontally (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:100779)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70556)
    at e.readDocument (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67407)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:324017)
```

### Commands

```
  2x -1:50.9.0 core:move-up (input.hidden-input)
     -1:50.2.0 core:paste (input.hidden-input)
     -1:49.5.0 editor:newline (input.hidden-input)
     -1:49.1.0 core:paste (input.hidden-input)
     -1:46.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:46.1.0 snippets:expand (input.hidden-input)
     -1:46.1.0 editor:indent (input.hidden-input)
     -1:44.6.0 snippets:next-tab-stop (input.hidden-input)
     -1:44.6.0 snippets:expand (input.hidden-input)
     -1:44.6.0 editor:indent (input.hidden-input)
  7x -1:40.8.0 core:backspace (input.hidden-input)
     -1:33 core:move-right (input.hidden-input)
 13x -1:32.5.0 core:backspace (input.hidden-input)
     -1:18.1.0 core:move-left (input.hidden-input)
  7x -1:17.7.0 core:backspace (input.hidden-input)
     -0:16.8.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
trueautomation-element-picker 2.1.8 
```

**Comment by ArtemDordovskyi** [comment]
Fixed in 2.1.9
